# Generated by Django 5.1.7 on 2025-03-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_social', models.CharField(blank=True, max_length=255, null=True)),
                ('contato', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=12, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('contato_emergencial', models.CharField(max_length=15)),
                ('responsavel', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_nascimento', models.DateField()),
                ('turma', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos_fotos/')),
            ],
        ),
    ]
