# Generated by Django 5.1.7 on 2025-03-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='id_aluno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='contato',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='contato_emergencial',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='periodo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(max_length=50),
        ),
    ]
