# Generated by Django 5.1.7 on 2025-03-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Alunos', '0002_aluno_id_aluno_alter_aluno_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='periodo',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde')], max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(choices=[('1ª Série', '1ª Série'), ('2ª Série', '2ª Série'), ('3ª Série', '3ª Série'), ('4ª Série', '4ª Série')], max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
    ]
