# Generated by Django 5.2.6 on 2025-09-17 02:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sistema_Alunos", "0003_alter_aluno_periodo_alter_aluno_serie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(default="fotos/default.jpg", upload_to="fotos/"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="serie",
            field=models.CharField(
                choices=[
                    ("1ª Ano", "1ª Ano"),
                    ("2ª Ano", "2ª Ano"),
                    ("3ª Ano", "3ª Ano"),
                    ("4ª Ano", "4ª Ano"),
                    ("5ª Ano", "5ª Ano"),
                    ("6ª Ano", "6ª Ano"),
                    ("7ª Ano", "7ª Ano"),
                    ("8ª Ano", "8ª Ano"),
                    ("9ª Ano", "9ª Ano"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bimestre1",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "bimestre2",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "bimestre3",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "bimestre4",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("media", models.FloatField(blank=True, null=True)),
                (
                    "aluno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="Sistema_Alunos.aluno",
                    ),
                ),
            ],
        ),
    ]
