# Generated by Django 5.2.6 on 2025-09-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Sistema_Alunos",
            "0004_alter_aluno_data_nascimento_alter_aluno_foto_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="deficiencia",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não")], default="N", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="deficiencia_qual",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="sexo",
            field=models.CharField(
                choices=[
                    ("M", "Masculino"),
                    ("F", "Feminino"),
                    ("NI", "Prefiro não informar"),
                ],
                default="NI",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="Nota",
        ),
    ]
