# Generated by Django 3.2.25 on 2026-03-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Alunos', '0005_aluno_deficiencia_aluno_deficiencia_qual_aluno_sexo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='rg',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default='fotos/default_rRsY7nC.png', upload_to='fotos/'),
        ),
    ]
