# Generated by Django 3.2.25 on 2026-03-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Alunos', '0006_auto_20260307_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
