"""
Django settings for Sistema_PI project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8gfta$(!=&!23%s0ke02hr%9^^o9tpfi@o2ijx$!tp$g051_4)'

DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1', 
    '177.128.8.236',
    'cidadedasrosas.shop',
    'www.cidadedasrosas.shop',
    'cidadedasrosas.duckdns.org',
    '.cidadedasrosas.shop',
    'web',
    '0.0.0.0',
    'zzlxwvvwec.loclx.io',
    '.loclx.io',
    'ntzo99tcym.loclx.io',
    # ADICIONE ESTE para o Cloudflare Tunnel:
    'b21a36a6-32a8-49a6-b0d9-98fcf52d4f0a.cfargotunnel.com',
    '.cfargotunnel.com',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://177.128.8.236:8000',
    'https://cidadedasrosas.shop',
    'https://www.cidadedasrosas.shop', 
    'https://cidadedasrosas.duckdns.org',
    'https://zzlxwvvwec.loclx.io',
    'https://*.loclx.io',
    'https://ntzo99tcym.loclx.io',
    # ADICIONE ESTE para o Cloudflare Tunnel:
    'https://b21a36a6-32a8-49a6-b0d9-98fcf52d4f0a.cfargotunnel.com',
]
# Configurações de segurança para produção
SECURE_SSL_REDIRECT = False  # Mude para True se usar HTTPS
SESSION_COOKIE_SECURE = False  # Mude para True se usar HTTPS
CSRF_COOKIE_SECURE = False    # Mude para True se usar HTTPS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Sistema_Alunos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Sistema_PI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sistema_PI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = '/login/'

# Tempo máximo de sessão inativa (10 minutos)
SESSION_COOKIE_AGE = 600  # 600 segundos = 10 minutos
SESSION_SAVE_EVERY_REQUEST = True  # Atualiza a sessão a cada requisição
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expira a sessão ao fechar o navegador


